<a href="https://colab.research.google.com/github/moatazkrimchi/Video_python/blob/main/Video_avec_python_COVID.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('https://opendata.ecdc.europa.eu/covid19/casedistribution/csv/data.csv')
df.head()

      dateRep  ...  Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
0  14/12/2020  ...                                           9.013779
1  13/12/2020  ...                                           7.052776
2  12/12/2020  ...                                           6.868768
3  11/12/2020  ...                                           7.134266
4  10/12/2020  ...                                           6.968658

[5 rows x 12 columns]

In [3]:
df = df[['dateRep', 'countriesAndTerritories', 'cases']]
df.head()

      dateRep countriesAndTerritories  cases
0  14/12/2020             Afghanistan    746
1  13/12/2020             Afghanistan    298
2  12/12/2020             Afghanistan    113
3  11/12/2020             Afghanistan     63
4  10/12/2020             Afghanistan    202

In [4]:
df.dtypes

dateRep                    object
countriesAndTerritories    object
cases                       int64
dtype: object

In [5]:
df['date'] = pd.to_datetime(df['dateRep'], dayfirst=True)

In [6]:
df

          dateRep countriesAndTerritories  cases       date
0      14/12/2020             Afghanistan    746 2020-12-14
1      13/12/2020             Afghanistan    298 2020-12-13
2      12/12/2020             Afghanistan    113 2020-12-12
3      11/12/2020             Afghanistan     63 2020-12-11
4      10/12/2020             Afghanistan    202 2020-12-10
...           ...                     ...    ...        ...
61895  25/03/2020                Zimbabwe      0 2020-03-25
61896  24/03/2020                Zimbabwe      0 2020-03-24
61897  23/03/2020                Zimbabwe      0 2020-03-23
61898  22/03/2020                Zimbabwe      1 2020-03-22
61899  21/03/2020                Zimbabwe      1 2020-03-21

[61900 rows x 4 columns]

In [7]:
df['total_cases'] = df.sort_values('date').groupby('countriesAndTerritories').cumsum().sort_index()

In [8]:
df

          dateRep countriesAndTerritories  cases       date  total_cases
0      14/12/2020             Afghanistan    746 2020-12-14        49273
1      13/12/2020             Afghanistan    298 2020-12-13        48527
2      12/12/2020             Afghanistan    113 2020-12-12        48229
3      11/12/2020             Afghanistan     63 2020-12-11        48116
4      10/12/2020             Afghanistan    202 2020-12-10        48053
...           ...                     ...    ...        ...          ...
61895  25/03/2020                Zimbabwe      0 2020-03-25            2
61896  24/03/2020                Zimbabwe      0 2020-03-24            2
61897  23/03/2020                Zimbabwe      0 2020-03-23            2
61898  22/03/2020                Zimbabwe      1 2020-03-22            2
61899  21/03/2020                Zimbabwe      1 2020-03-21            1

[61900 rows x 5 columns]

In [9]:
df = df[['date', 'countriesAndTerritories', 'total_cases']]
df = df.rename(columns={'countriesAndTerritories': 'country'})
df

            date      country  total_cases
0     2020-12-14  Afghanistan        49273
1     2020-12-13  Afghanistan        48527
2     2020-12-12  Afghanistan        48229
3     2020-12-11  Afghanistan        48116
4     2020-12-10  Afghanistan        48053
...          ...          ...          ...
61895 2020-03-25     Zimbabwe            2
61896 2020-03-24     Zimbabwe            2
61897 2020-03-23     Zimbabwe            2
61898 2020-03-22     Zimbabwe            2
61899 2020-03-21     Zimbabwe            1

[61900 rows x 3 columns]

In [10]:
df = pd.pivot_table(df, index=['date'], columns=['country'], values=['total_cases'])
df

           total_cases                    ...
country    Afghanistan  Albania  Algeria  ...   Yemen   Zambia Zimbabwe
date                                      ...
2019-12-31         0.0      NaN      0.0  ...     NaN      NaN      NaN
2020-01-01         0.0      NaN      0.0  ...     NaN      NaN      NaN
2020-01-02         0.0      NaN      0.0  ...     NaN      NaN      NaN
2020-01-03         0.0      NaN      0.0  ...     NaN      NaN      NaN
2020-01-04         0.0      NaN      0.0  ...     NaN      NaN      NaN
...                ...      ...      ...  ...     ...      ...      ...
2020-12-10     48053.0  45188.0  90014.0  ...  2079.0  18062.0  11007.0
2020-12-11     48116.0  46061.0  90579.0  ...  2081.0  18091.0  11081.0
2020-12-12     48229.0  46863.0  91121.0  ...  2082.0  18161.0  11162.0
2020-12-13     48527.0  47742.0  91638.0  ...  2083.0  18217.0  11219.0
2020-12-14     49273.0  48530.0  92102.0  ...  2083.0  18274.0  11246.0

[350 rows x 214 columns]

In [11]:
df.columns

MultiIndex([('total_cases',         'Afghanistan'),
            ('total_cases',             'Albania'),
            ('total_cases',             'Algeria'),
            ('total_cases',             'Andorra'),
            ('total_cases',              'Angola'),
            ('total_cases',            'Anguilla'),
            ('total_cases', 'Antigua_and_Barbuda'),
            ('total_cases',           'Argentina'),
            ('total_cases',             'Armenia'),
            ('total_cases',               'Aruba'),
            ...
            ('total_cases',             'Uruguay'),
            ('total_cases',          'Uzbekistan'),
            ('total_cases',             'Vanuatu'),
            ('total_cases',           'Venezuela'),
            ('total_cases',             'Vietnam'),
            ('total_cases',   'Wallis_and_Futuna'),
            ('total_cases',      'Western_Sahara'),
            ('total_cases',               'Yemen'),
            ('total_cases',              'Zambia'),
            ('total_cases',            'Zimbabwe')],
           names=[None, 'country'], length=214)

In [12]:
df.index.name = None
df.columns = [col[1] for col in df.columns]
df

            Afghanistan  Albania  Algeria  ...   Yemen   Zambia  Zimbabwe
2019-12-31          0.0      NaN      0.0  ...     NaN      NaN       NaN
2020-01-01          0.0      NaN      0.0  ...     NaN      NaN       NaN
2020-01-02          0.0      NaN      0.0  ...     NaN      NaN       NaN
2020-01-03          0.0      NaN      0.0  ...     NaN      NaN       NaN
2020-01-04          0.0      NaN      0.0  ...     NaN      NaN       NaN
...                 ...      ...      ...  ...     ...      ...       ...
2020-12-10      48053.0  45188.0  90014.0  ...  2079.0  18062.0   11007.0
2020-12-11      48116.0  46061.0  90579.0  ...  2081.0  18091.0   11081.0
2020-12-12      48229.0  46863.0  91121.0  ...  2082.0  18161.0   11162.0
2020-12-13      48527.0  47742.0  91638.0  ...  2083.0  18217.0   11219.0
2020-12-14      49273.0  48530.0  92102.0  ...  2083.0  18274.0   11246.0

[350 rows x 214 columns]

In [13]:
df = df.fillna(0).astype(int)
df

            Afghanistan  Albania  Algeria  ...  Yemen  Zambia  Zimbabwe
2019-12-31            0        0        0  ...      0       0         0
2020-01-01            0        0        0  ...      0       0         0
2020-01-02            0        0        0  ...      0       0         0
2020-01-03            0        0        0  ...      0       0         0
2020-01-04            0        0        0  ...      0       0         0
...                 ...      ...      ...  ...    ...     ...       ...
2020-12-10        48053    45188    90014  ...   2079   18062     11007
2020-12-11        48116    46061    90579  ...   2081   18091     11081
2020-12-12        48229    46863    91121  ...   2082   18161     11162
2020-12-13        48527    47742    91638  ...   2083   18217     11219
2020-12-14        49273    48530    92102  ...   2083   18274     11246

[350 rows x 214 columns]

In [14]:
df['Cases_on_an_international_conveyance_Japan']

2019-12-31    0
2020-01-01    0
2020-01-02    0
2020-01-03    0
2020-01-04    0
             ..
2020-12-10    0
2020-12-11    0
2020-12-12    0
2020-12-13    0
2020-12-14    0
Name: Cases_on_an_international_conveyance_Japan, Length: 350, dtype: int64

In [15]:
df = df.drop(columns=['Cases_on_an_international_conveyance_Japan'])
df

            Afghanistan  Albania  Algeria  ...  Yemen  Zambia  Zimbabwe
2019-12-31            0        0        0  ...      0       0         0
2020-01-01            0        0        0  ...      0       0         0
2020-01-02            0        0        0  ...      0       0         0
2020-01-03            0        0        0  ...      0       0         0
2020-01-04            0        0        0  ...      0       0         0
...                 ...      ...      ...  ...    ...     ...       ...
2020-12-10        48053    45188    90014  ...   2079   18062     11007
2020-12-11        48116    46061    90579  ...   2081   18091     11081
2020-12-12        48229    46863    91121  ...   2082   18161     11162
2020-12-13        48527    47742    91638  ...   2083   18217     11219
2020-12-14        49273    48530    92102  ...   2083   18274     11246

[350 rows x 213 columns]

In [16]:
df.columns = [col.replace('_', ' ') for col in df.columns]

In [17]:
country_reserved = set()
for index, row in df.iterrows():
    country_reserved |= set(row[row > 0].sort_values(ascending=False).head(10).index)
df = df[list(country_reserved)]

In [19]:
df

               Iran  South Korea    Peru  ...    Italy    Spain   Russia
2019-12-31        0            0       0  ...        0        0        0
2020-01-01        0            0       0  ...        0        0        0
2020-01-02        0            0       0  ...        0        0        0
2020-01-03        0            0       0  ...        0        0        0
2020-01-04        0            0       0  ...        0        0        0
...             ...          ...     ...  ...      ...      ...      ...
2020-12-10  1072620        40098  977312  ...  1770149  1720056  2541199
2020-12-11  1083023        40786  979111  ...  1787147  1730575  2569126
2020-12-12  1092617        41736  980943  ...  1805873  1730575  2597711
2020-12-13  1100818        42766  983045  ...  1825775  1730575  2625848
2020-12-14  1108269        43484  984973  ...  1843712        0  2653928

[350 rows x 30 columns]

In [18]:
!pip install bar-chart-race

Collecting bar-chart-race
  Downloading bar_chart_race-0.1.0-py3-none-any.whl (156 kB)
     |████████████████████████████████| 156 kB 4.9 MB/s
Requirement already satisfied: matplotlib>=3.1 in /usr/local/lib/python3.7/dist-packages (from bar-chart-race) (3.2.2)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.7/dist-packages (from bar-chart-race) (1.1.5)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.1->bar-chart-race) (1.3.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.1->bar-chart-race) (3.0.6)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.1->bar-chart-race) (2.8.2)
Requirement already satisfied: numpy>=1.11 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.1->bar-chart-race) (1.19.5)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.1->bar-chart-race) (0.11.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24->bar-chart-race) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=3.1->bar-chart-race) (1.15.0)
Installing collected packages: bar-chart-race
Successfully installed bar-chart-race-0.1.0

In [21]:
import bar_chart_race as bcr

In [24]:
bcr.bar_chart_race(
    df=df,
    filename='/content/video.mp4',
    n_bars=10,
    period_fmt='%B %d, %Y',
    title='COVID-19 Confirmed Cases by Country'
)